# Generated by Django 4.2.6 on 2023-10-29 19:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoModo', models.CharField(choices=[('CPE', 'Equipo local cliente'), ('AP', 'Acces point'), ('RT', 'Router')], max_length=250, verbose_name='Modo')),
            ],
            options={
                'verbose_name': 'tipo de modo',
                'verbose_name_plural': 'tipos de modos',
                'db_table': 'Modo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Calle n°')),
                ('tira_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tira')),
                ('piso_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('departamento_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento')),
                ('casa_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Casa')),
                ('puerta_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Puerta')),
                ('seccion_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sección')),
                ('parcela_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parcela')),
                ('manzana_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Manzana')),
                ('macizo_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Macizo')),
                ('lote_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote')),
                ('latitud', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitud')),
                ('marca', models.CharField(max_length=250, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=250, verbose_name='Modelo')),
                ('barrio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='localidad', chained_model_field='localidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='localizacion.barrio', verbose_name='Barrio')),
                ('calle', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='barrio', chained_model_field='barrio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_calle', to='localizacion.calle', verbose_name='Calle')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localizacion.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
    ]
