# Generated by Django 4.2.6 on 2023-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('descipcion_ampliada', models.TextField(blank=True, max_length=500, null=True, verbose_name='descripcion ampliada')),
            ],
            options={
                'verbose_name': 'tipo cliente',
                'verbose_name_plural': 'tipos de clientes',
                'db_table': 'tipo_cliente',
                'ordering': ['id'],
            },
        ),
    ]
