# Generated by Django 4.2.6 on 2023-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteTipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientetipo',
            name='descipcion_ampliada',
        ),
        migrations.AddField(
            model_name='clientetipo',
            name='descripcion_ampliada',
            field=models.TextField(default=None, verbose_name='Descricion ampliada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientetipo',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
