# Generated by Django 4.2.6 on 2023-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteTipo', '0002_remove_clientetipo_descipcion_ampliada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientetipo',
            name='activo',
            field=models.BooleanField(default=None, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
