# Generated by Django 4.2.6 on 2023-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoImpuesto', models.CharField(choices=[('Consumidor final', 'Consumidor final'), ('Exento', 'Exento'), ('Monotributo', 'Mono tributo'), ('Responsable inscripto', 'Responsable inscripto')], max_length=250, verbose_name='Tipo de impuesto')),
            ],
            options={
                'verbose_name': 'tipoImpuesto',
                'verbose_name_plural': 'Tipo impuestos',
                'db_table': 'tipoImpuesto',
                'ordering': ['id'],
            },
        ),
    ]
