# Generated by Django 4.2.6 on 2023-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoimpuesto',
            name='tipoImpuesto',
            field=models.CharField(choices=[('Consumidor final', 'Consumidor final'), ('Exento', 'Exento'), ('Monotributo', 'Mono tributo'), ('Responsable inscripto', 'Responsable inscripto'), ('Protocolar', 'Protocolar')], max_length=250, verbose_name='Tipo de impuesto'),
        ),
    ]
