# Generated by Django 4.2.6 on 2023-10-29 18:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('localizacion', '0001_initial'),
        ('clienteTipo', '0003_clientetipo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('tipoimpuesto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configuracion.tipoimpuesto')),
                ('prefijo_celular', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prefijo celular')),
                ('celular_nro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nro. celular')),
                ('prefijo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prefijo')),
                ('telefono_nro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nro. teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('calle_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Calle n°')),
                ('tira_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tira')),
                ('piso_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('departamento_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento')),
                ('casa_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Casa')),
                ('puerta_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Puerta')),
                ('seccion_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sección')),
                ('parcela_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parcela')),
                ('manzana_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Manzana')),
                ('macizo_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Macizo')),
                ('lote_nro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote')),
                ('latitud', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitud')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, null=True, verbose_name='Apellido')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('tipo_documento', models.CharField(max_length=10, verbose_name='Tipo de documento')),
                ('documento_nro', models.CharField(max_length=12, verbose_name='Numero de documento')),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(verbose_name='Estado cliente')),
                ('barrio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='localidad', chained_model_field='localidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='localizacion.barrio', verbose_name='Barrio')),
                ('calle', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='barrio', chained_model_field='barrio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_calle', to='localizacion.calle', verbose_name='Calle')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='localizacion.localidad', verbose_name='Localidad')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clienteTipo.clientetipo', verbose_name='Tipo de cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
                'unique_together': {('documento_nro',)},
            },
            bases=('configuracion.tipoimpuesto', models.Model),
        ),
    ]
