# Generated by Django 4.2.6 on 2023-10-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antena', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='antena.modo', verbose_name='Modo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='antena.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_nro',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de documento'),
        ),
    ]
